#pragma once

#include <stdint.h>

/* ================= CAN ID Macros ================= */

#define CAN_ID_BPS_VT0_VOLTAGE_ARR 0x2
#define CAN_ID_BPS_VT1_VOLTAGE_ARR 0x3
#define CAN_ID_BPS_VT2_VOLTAGE_ARR 0x4
#define CAN_ID_BPS_VT3_VOLTAGE_ARR 0x5
#define CAN_ID_BPS_VT4_VOLTAGE_ARR 0x6
#define CAN_ID_BPS_VT5_VOLTAGE_ARR 0x7
#define CAN_ID_BPS_VT6_VOLTAGE_ARR 0x8
#define CAN_ID_BPS_VT7_VOLTAGE_ARR 0x9
#define CAN_ID_BPS_PACK_CURRENT 0xA
#define CAN_ID_BPS_VT0_TEMPERATURE_ARR 0x10
#define CAN_ID_BPS_VT1_TEMPERATURE_ARR 0x11
#define CAN_ID_BPS_VT2_TEMPERATURE_ARR 0x12
#define CAN_ID_BPS_VT3_TEMPERATURE_ARR 0x13
#define CAN_ID_BPS_VT4_TEMPERATURE_ARR 0x14
#define CAN_ID_BPS_VT5_TEMPERATURE_ARR 0x15
#define CAN_ID_BPS_VT6_TEMPERATURE_ARR 0x16
#define CAN_ID_BPS_VT7_TEMPERATURE_ARR 0x17
#define CAN_ID_BPS_PACK_CURRENT_RAWV 0x755
#define CAN_ID_BPS_BALANCE_DISCHARGE 0x7A0

/* ================= CAN Length Macros ================= */

#define CAN_DLC_BPS_VT0_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT1_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT2_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT3_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT4_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT5_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT6_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT7_VOLTAGE_ARR 4
#define CAN_DLC_BPS_PACK_CURRENT 5
#define CAN_DLC_BPS_VT0_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT1_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT2_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT3_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT4_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT5_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT6_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT7_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_PACK_CURRENT_RAWV 3
#define CAN_DLC_BPS_BALANCE_DISCHARGE 1


/* ================= Value Table Enums ================= */

typedef enum {
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt0_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt1_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt2_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt3_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt4_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt5_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt6_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt7_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OK = 0,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OUT_OF_BOUNDS = 1,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OVER_CURRENT_DISCHARGE_ = 2,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OVER_CURRENT_CHARGE_ = 3,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_MESSAGE_WATCHDOG = 4,
} bps_pack_current_bps_amperes_fault_e;

typedef enum {
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt0_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt1_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt2_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt3_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt4_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt5_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt6_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt7_temperature_arr_bps_temperature_tap_fault_e;

/* ================= Message Structs ================= */

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt0_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt1_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt2_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt3_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt4_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt5_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt6_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt7_voltage_arr_t;

typedef struct {
    uint8_t BPS_Amperes_Fault;
    int32_t Main_Battery_Current;
    uint8_t FrameID_Amperes;
} bps_pack_current_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt0_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt1_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt2_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt3_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt4_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt5_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt6_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_RawV;
} bps_vt7_temperature_arr_t;

typedef struct {
    uint16_t Main_Battery_Current_RawV;
    uint8_t FrameID_Amperes;
} bps_pack_current_rawv_t;

typedef struct {
    uint8_t BPS_Segment_idx;
    uint8_t BPS_Tap_idx;
} bps_balance_discharge_t;

