#pragma once
#include "CAN.h"

#define VOLTTEMP_MSG_DLC 7

#ifdef VOLTTEMP_0
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT0_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT0_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT0_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT0_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_1)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT1_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT1_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT1_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT1_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {4, 5, 6, 7};
#elif defined(VOLTTEMP_2)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT2_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT2_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT2_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT2_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {8, 9, 10, 11};
#elif defined(VOLTTEMP_3)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT3_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT3_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT3_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT3_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {12, 13, 14, 15};
#elif defined(VOLTTEMP_4)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT4_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT4_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT4_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT4_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {16, 17, 18, 19};
#elif defined(VOLTTEMP_5)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT5_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT5_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT5_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT5_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {20, 21, 22, 23};
#elif defined(VOLTTEMP_6)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT6_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT6_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT6_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT6_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {24, 25, 26, 27};
#elif defined(VOLTTEMP_7)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VT7_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_VT7_TEMPERATURE_ARR
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VT7_VOLTAGE_ARR
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_VT7_TEMPERATURE_ARR
    static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {28, 29, 30, 31};
#else
    #error "Invalid volttemp defined, must be within range of 0-7"
#endif