#include "CAN.h"

//Finish this when main is being developed.

typedef enum{ 
    VOLTTEMP_OK,
    VOLTTEMP_READ_FAIL,
    VOLTTEMP_INIT_FAIL,
    VOLTTEMP_ADC_FAIL,
    VOLTTEMP_QUEUE_FULL,
    VOLTTEMP_CAN_SEND_FAIL
} VoltTempStatus_t;

#define VOLTTEMP_MSG_DLC 7

#ifdef VOLTTEMP_0
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_0
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_0
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_0
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_0
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_1)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_1
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_1
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_1
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_1
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_2)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_2
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_2
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_2
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_2
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_3)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_3
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_3
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_3
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_3
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_4)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_4
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_4
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_4
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_4
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_5)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_5
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_5
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_5
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_5
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_6)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_6
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_6
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_6
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_6
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#elif defined(VOLTTEMP_7)
    #define CAN_ID_VOLTAGE_MSG          CAN_ID_BPS_VOLTAGE_ARR_7
    #define CAN_ID_TEMPERATURE_MSG      CAN_ID_BPS_TEMPERATURE_ARR_7
    #define CAN_ID_VOLTAGE_MSG_DLC      CAN_DLC_BPS_VOLTAGE_ARR_7
    #define CAN_ID_TEMPERATURE_MSG_DLC  CAN_DLC_BPS_TEMPERATURE_ARR_7
    // static uint8_t tapIdxArr[NUM_VOLTAGES_PER_VOLTTEMP] = {0, 1, 2, 3};
#else
    #error "Invalid volttemp defined, must be within range of 0-7"
#endif