# ----- BPS-Leader Makefile -----

# crazy colors ------------------
RED=\033[0;31m
GREEN=\033[0;32m
ORANGE=\033[0;33m
BLUE=\033[0;34m
PURPLE=\033[0;35m
CYAN=\033[0;36m
LIGHTGRAY=\033[0;37m
DARKGRAY=\033[1;30m
YELLOW=\033[0;33m
NC=\033[0m # No Color
#---------------------------------

# Define the C_DEFS variable using the value of VOLTTEMP
PROJECT_MACROS = VOLTTEMP_$(VOLTTEMP) USART1_TX_QUEUE_SIZE=100

# Project Configuration ----------
TEST ?= main
PROJECT_TARGET ?= stm32l431cbt

# source and include directories
PROJECT_C_INCLUDES = $(wildcard */Inc) $(wildcard */inc) $(wildcard */include)
PROJECT_C_SOURCES = $(wildcard */Src/*.c)


# build directories
PROJECT_BUILD_DIR = build
BUILD_MAKEFILE_DIR = Embedded-Sharepoint

# generate paths	
MAKEFILE_DIR = $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

PROJECT_MAIN_DIR ?= core/Src/main

ifneq ($(TEST), main)
PROJECT_C_SOURCES := $(filter-out $(PROJECT_MAIN_DIR).c, $(PROJECT_C_SOURCES))
PROJECT_C_SOURCES := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_C_SOURCES) tests/$(TEST).c)
else
PROJECT_C_SOURCES := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_C_SOURCES))
endif

# debug
ifeq ($(PRINT_DEBUG), true)
$(info SOURCES: $(PROJECT_C_SOURCES))
$(info INCLUDES: $(PROJECT_C_INCLUDES))
endif

# generate paths (cont.d)
PROJECT_C_INCLUDES := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_C_INCLUDES))
PROJECT_BUILD_DIR := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_BUILD_DIR))

# export variables 
export PROJECT_TARGET
export PROJECT_C_SOURCES
export PROJECT_C_INCLUDES
export PROJECT_BUILD_DIR
export PROJECT_MACROS

#-------------------------------
# Clang
BEAR_PREFIX := 
# check if bear is installed
BEAR_INSTALLED := $(shell command -v bear >/dev/null 2>&1 && echo yes || echo no)

# define path of .vscode
VS_CODE_DIR := $(realpath ../.vscode/)

ifeq ($(BEAR_INSTALLED),yes)
	ifneq ($(VS_CODE_DIR),)
		BEAR_PREFIX := bear --output $(VS_CODE_DIR)/compile_commands.json --append --
	endif
else
	BEAR_PREFIX :=
endif


# Build --------------------------
ifeq ($(MAKECMDGOALS),)
default: build_code
else ifeq ($(MAKECMDGOALS), all)
all: build_code
else
%:
	$(BEAR_PREFIX) $(MAKE) -C $(BUILD_MAKEFILE_DIR) $(MAKECMDGOALS)
endif

build_code:
ifndef VOLTTEMP
	$(error VOLTTEMP is not defined. Please provide a volttemp to build for. Run make help for more information.)
endif
ifneq ($(TEST), main)
	@echo -e "Making ${PURPLE}$(PROJECT_TARGET)${NC}build for ${BLUE}TEST=${PURPLE} ${TEST}${NC}"
else
	@echo -e "Making ${PURPLE}$(PROJECT_TARGET)${NC}build with ${ORANGE}no test.${NC}"
endif
	$(BEAR_PREFIX) $(MAKE) -C $(BUILD_MAKEFILE_DIR) VERBOSE=1 all -j
	@echo -e "${BLUE}Compiled! Splendid! Jolly Good!!${NC}"
#---------------------------------


#-------------------------------
# Flash
flash: 	
	$(MAKE) -C $(BUILD_MAKEFILE_DIR) flash

# Help
.PHONY: help
help:
	@echo "Format: ${ORANGE}make ${GREEN}VOLTTEMP=${PURPLE}<volttemp target (0-7)>${NC} ${BLUE}TEST=${PURPLE}<Test name>${NC}"

	@echo -e "${BLUE}TEST${NC}( OPTIONAL ):"
	@echo -e "- If you want to run a test, specify ${BLUE}TEST=${PURPLE}<Test name>${NC}, with ${PURPLE}<Test name>${NC}"
	@echo -e "   being the exact name of the test file ${RED} without${NC} the .c suffix.\n"
#-------------- 
# Documentation
# .PHONY: docs
# docs:
# 	cd $(BUILD_MAKEFILE_DIR) && mkdocs serve
